# ServerProperties
server:
  port: 8080
  servlet:
    context-path: /community # 给项目加上路径
spring:
  thymeleaf: # ThymeleafProperties
    cache: false # 关闭thymeleaf的缓存
  datasource: # mysql数据源（连接池）
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?useSSL=false
    username: root
    password: xxx
    type: com.zaxxer.hikari.HikariDataSource # 连接池配置
    hikari:
      maximum-pool-size: 15 # 最大连接数
      minimum-idle: 5 # 最小的连接保留数
      idle-timeout: 3000 # 等待关闭的毫秒数
  mail:
    host: smtp.163.com
    username: huangruidong666@163.com
    password: xxx
    protocol: smtp
    default-encoding: UTF-8
  redis:
    database: 1
    host: 192.168.184.100
    port: 6379
    password: xxx
  kafka:
    bootstrap-servers: 192.168.184.100:9092
    consumer:
      enable-auto-commit: true
      auto-commit-interval: 3000
      group-id: test-consumer-group

mybatis:
  mapper-locations: classpath:mapper/*.xml # 映射文件位置 classpath: 打包后就是target.classes包下
  type-aliases-package: com.nowcoder.community.pojo # 实体类的包名
  configuration:
    use-generated-keys: true # 启动自动生成id的组件
    map-underscore-to-camel-case: true # 下划线转驼峰

community:
  path:
    domain: http://localhost:8080
    upload: d:/project/data/upload

#logging:
#  level:
#    com.nowcoder.community: warn # 修改日志级别，调为较低的debug模式，方便检查mapper写的对不对
#  file:
#    name: community.log